# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{boned}
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Delano Mandelbaum"]
  s.date = %q{2010-12-17}
  s.default_executable = %q{boned}
  s.description = %q{HTTP server companion for Bone (remote environment variables)}
  s.email = %q{delano@solutious.com}
  s.executables = ["boned"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "CHANGES.txt",
     "LICENSE.txt",
     "README.md",
     "Rakefile",
     "VERSION.yml",
     "api/api-set.rb",
     "api/api.rb",
     "app.ru",
     "bin/boned",
     "boned.gemspec",
     "config/redis-server.conf",
     "lib/boned.rb",
     "lib/boned/api.rb",
     "lib/boned/api/base.rb",
     "lib/boned/app.rb",
     "public/index.html",
     "try/10_basics_try.rb",
     "try/11_signature_try.rb",
     "try/20_keys_try.rb",
     "views/redisviewer/keys.erb"
  ]
  s.homepage = %q{https://github.com/solutious/boned}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{boned}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{HTTP server companion for Bone (remote environment variables)}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bone>, [">= 0.3.0"])
      s.add_runtime_dependency(%q<sinatra>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<thin>, [">= 0"])
    else
      s.add_dependency(%q<bone>, [">= 0.3.0"])
      s.add_dependency(%q<sinatra>, [">= 1.0.0"])
      s.add_dependency(%q<thin>, [">= 0"])
    end
  else
    s.add_dependency(%q<bone>, [">= 0.3.0"])
    s.add_dependency(%q<sinatra>, [">= 1.0.0"])
    s.add_dependency(%q<thin>, [">= 0"])
  end
end

